### ISSUE TITLE
Açık kaynağa giriş belgeleri

### ISSUE THREAD

**Issue by aliok** [OpenTRFoundation/OpenTR#16]
Hedefimiz katkı belgeleri hazırlamak olsa da, açık kaynağa giriş için bazı belgeler hazırlamamız da gerekiyor.

Hepsi özet şekilde:
- Açık kaynak tanımı
- Büyük açık kaynak projeler
- Açık kaynağın tarihçesi
- Modern açık kaynak ve farkları
- Terimler: topluluk, mailing list, ...

**Comment by aliok** [comment]
Merhaba @mugekocahan @altuga 

Şurada ne gibi başlıklar olacağına dair bir Google doc hazırladım: https://docs.google.com/document/d/1Tb70mtu-D5KihpWEQ6nrLfSRSyvz43kKcKhi6zl0olE/edit

Bu belgenin bağlamı şu:

- OpenTR’de açık kaynağa katkı konusunda çalışmak istiyoruz.
- Ancak, açık kaynak nedir diye bir referans belgemiz olsa, oldukça güzel olur.
- Hedef kitle:
  - Açık kaynak konusunu öğrenmek isteyenler
  - Açık kaynağa zaruri geçiş yapacaklar (kamu kurumları gibi)
  - OpenTR katılımcıları: konuşmalarda ve belgelerde referans verebilmek için
  - Açık kaynağa katkı yapmak isteyen, ama lisanslar vb. gibi konuları bilmeyenler
  - OpenTR’yi tanımak isteyenler: OpenTR çatısı altındaki kaliteli referans dokümanlarını kullanarak, katılımcı ve ilgi çekebiliriz.

**Comment by aliok** [comment]
Belgeleri bu yorumda toplayacağım.

- [Başlıklar](https://docs.google.com/document/d/1Tb70mtu-D5KihpWEQ6nrLfSRSyvz43kKcKhi6zl0olE/edit)
- [Açık kaynak nedir?](https://docs.google.com/document/d/1B5dzwiixfQdWQA_4-XFX1TAqD2I70gXofY-hQ_L6Ub0/edit#heading=h.ptaea9hu3134)
- [Açık Kaynağın Etkisi](https://docs.google.com/document/d/1YYo-fBYt57_LzN3rSzoojSNoy9sGpEi2_H4kbdu9FLc/edit#heading=h.lpejl6gue9qm)

**Comment by mugekocahan** [comment]
Merhabalar,

Toplantı kaydı ve doküman paylaşımları için teşekkürler.
Aşağıda ben de iki doküman paylaşmak istedim Açık Kaynağın Etkisi başlıklı
doküman için katkı sağlayabilir.

Avrupa Birliği Komisyonunun açık kaynar stratejisi ve etkileri üzerinde iki
çalışma raporu;

https://digital-strategy.ec.europa.eu/en/library/study-about-impact-open-source-software-and-hardware-technological-independence-competitiveness-and

https://commission.europa.eu/about-european-commission/departments-and-executive-agencies/informatics/open-source-software-strategy_en

Şu anda acaba daha önce paylaşmış mıydım diye bi şüphe oluştu bende ama,
öyleyse kusura bakmayın :)

Görüşmek üzere
Müge

Ali Ok ***@***.***>, 10 Eyl 2023 Paz, 02:18 tarihinde şunu
yazdı:

**Comment by aliok** [comment]
Teşekkürler @mugekocahan 

Açık Kaynağın Etkisi belgesinde ilk rapordan alıntı yapmıştım. Ama ikincisine de bakayım.

**Comment by aliok** [comment]
PRlar:
- https://github.com/OpenTRFoundation/OpenTR/pull/27
- https://github.com/OpenTRFoundation/OpenTR/pull/30
- https://github.com/OpenTRFoundation/OpenTR/pull/31

Tamamlandi
