### ISSUE TITLE
Veri madenciği araştırması - ilk iterasyon

### ISSUE THREAD

**Issue by aliok** [OpenTRFoundation/OpenTR#20]
https://github.com/OpenTRFoundation/OpenTR/issues/18 'in alt görevidir.

Anket dışında, online bulabileceğimiz veri kaynakları var mıdır?

- GitHub API ile Türkiye bazlı veri kırılımı görebilir miyiz?
- StackOverflow
- ...

**Comment by altuga** [comment]
Github da yaptığım araştırmada tag üzerinden iki  kırılım buldum - https://github.com/topics/turkey  ve https://github.com/topics/turkish  ama bu tagleme ne kadarı opensource kapsamına girer bilemiyorum.,


--------------------------------------------------
StackOverflow üzerinden çok sağlıklı bir veri bulamadım

--------------------------------------------------
turkiyeacikkaynakplatformu üzerinden 5 proje buldum 

1  - https://www.turkiyeacikkaynakplatformu.com/turkce-dogal-dil-isleme-projesi/
2 - https://www.turkiyeacikkaynakplatformu.com/pardus-yayginlastirilmasi-projesi/
3 - https://www.turkiyeacikkaynakplatformu.com/acik-kaynak-sistemleri-yayginlastirma-akasya-projesi/
4 - https://www.turkiyeacikkaynakplatformu.com/skill-badge-projesi/
5 - https://www.turkiyeacikkaynakplatformu.com/kubernetes-orkestrasyonu-sistemi-projesi/

Şimdilik bulabildiklerim bu kadar

**Comment by aliok** [comment]
Benim bulabildiğim veri kaynakları şunlar:

### GitHub Search

- Konumuna Türkiye yazan GitHub kullanıcıları: https://github.com/search?q=location%3Aturkey&type=users&p=1
  - "Turkey" diye aratınca, iller de dahil oluyor. İlçeleri denemedim.
  - "Türkiye" diye aratınca ayrı sonuçlar geliyor, ikisini birleştirmek lazım.
- https://github.com/search/advanced adresindeki şeyleri kullanarak aratılacak query üretilebiliyor. Mesela, Türkiye'den en az 200 public repo'su olan ve en az 150 follower'ı olan kişiler: https://github.com/search?q=location%3ATurkey+repos%3A%3E200+followers%3A%3E150&type=users&ref=advsearch
- Buradan ama PR ve profil detayları birleştirilemiyor. Mesela, en az 5K star' olan bir projeye Türkiye'den PR açanları aramak mümkün değil. Bunun için GitHub'ın GraphQL API'sini kullanmak gerekiyor.

---
 
<img width="797" alt="Screenshot 2023-09-16 at 23 35 41" src="https://github.com/OpenTRFoundation/OpenTR/assets/376732/938f3fb0-d088-4030-954e-e7007ba6f958">

---

<img width="1017" alt="Screenshot 2023-09-16 at 23 35 30" src="https://github.com/OpenTRFoundation/OpenTR/assets/376732/9ee82222-d0f0-4d97-a378-a175ba4ba6d1">

---

<img width="720" alt="Screenshot 2023-09-16 at 23 57 43" src="https://github.com/OpenTRFoundation/OpenTR/assets/376732/41640336-09d5-4d14-b12e-509477c9b4e8">

### GitHub GraphQL API

(detaylarini yazacagim)

### gharchive

(detaylarini yazacagim)

### gharchive bigquery

(detaylarini yazacagim)

### DevStats

(detaylarini yazacagim)

Devstats, CNCF
https://all.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=Turkey

**Comment by aliok** [comment]
GitHub verisi ile elde edilebilecek analizler:
1. Türkiye'deki GitHub kullanıcı sayısı ve diğer ülkeler ile kıyaslaması
  - Ancak, sadece konumuna Türkiye yazan kullanıcıları bulabiliriz. Herkes yazmıyor ama, boş bırakan sayısının oranını kabataslak tahmin etmeye yönelik bir yöntem gerekiyor.
2. Türkiye'den açık kaynak projelere katkı yapan kişi sayısı
  - Türkiye'den PR açan kişi sayısını bulabiliriz.
  - Ancak, PR'ların açıldığı proje gerçekten bizim ilgimizi çeken açık kaynak projelerden mi?
  - Mesela, ben kendi boş repo'ma bir PR açtığımda o da çıkacak.
  - Proje belirlemek için farklı kriterler geliştirmemiz  gerekiyor. Mesela şunların birleşimi:
    - Bazı bilindik GitHub organizasyonlarının listesi (mesela ASF, tüm projelerini github.com/apache altına koyuyor)
    - Bazı bilindik projelerin listesi (CNCF projeleri ayrı GitHub organizasyonlarının altında, ama CNCF'te bir organizasyon/proje listesi var)
    - Belirli sayıdan fazla star almış olan GitHub organizasyonları ve/veya projeleri
    - Belirli bir sayıdan fazla forklanmış olan GitHub organizasyonları ve/veya projeleri
    - ...
3. Türklerin liderlik/committer'lık/vb. yaptığı projeler
  - Üstteki projelerde bir kişinin commit sayısını, toplam commit sayısına bölerek belki bir oranı kullanabiliriz.

**Comment by altuga** [comment]
Eline sağlık, epey detaylı veriler var.
Türkiye 'de açık kaynak proje destek vermek ne demek, tanımı iyi ortaya koymak lazım.
Dediğin gibi geliştirici kendi açtığı veya okul projesine PR açmış olabilir.  
Kriter olarak turkiyeacikkaynakplatformu üzerinden 5 proje eklemiştim. 
Senin bahsettiğin kriterlerle ile genişletebilir ama bir şekilde belirli varsayımlara dayanmak zorundayız.

Br sonraki plan nedir?

**Comment by aliok** [comment]
@altuga hocam selamlar,

> Türkiye 'de açık kaynak proje destek vermek ne demek, tanımı iyi ortaya koymak lazım.
> Dediğin gibi geliştirici kendi açtığı veya okul projesine PR açmış olabilir.

Aynen hocam. Buna kafa yormamız lazım.

Biraz terminoloji uydurmaya ihtiyacımız var aslında. Çünkü, GitHub'daki her public proje aslında bir açık kaynak proje. Ama, bu demek değil ki bunlar bizim için önemli.
Bizim için önemli olan, katkıcı sayısını artırmak istediğimiz projelere bir isim bulmamız lazım. Mesela, "stratejik açık kaynak proje" gibi bir şey.

Stratejik proje terminolojisini devam ettirecek olursam,  benim hep aklımdan geçen ASF, JCP, CNCF gibi yerlere katkı yapan kişilerin sayısını artırmak idi. Yani bu kişileri ben "açık kaynağa katkı veren kişiler" olarak tanımlıyordum kafamda. Bunları da stratejik açık kaynak projeler. Ama, çok fazla yer ve proje var.

Sanırım, üstte de bahsettiğim organizasyonlar gibi hardcoded bir listedeki organizasyonların repo'larına belirli bir PR'dan fazla açan kişileri "stratejik proje contributor'u" sınıfına dahil edebiliriz.

Hardcoded listemizde olmayan, atladığımız projeler mutlaka olacaktır (hatta çoğunluğu öyle olacaktır). 

Burada da, bir kriter geliştirebiliriz. Atıyorum, aşağıdaki kriterleri sağlayan projeler "stratejik proje"dir diyebiliriz:
- Belirli bir contributor sayısından fazla: Türkiye'den katkı sayısını artırmayı hedeflediğimiz repo'ların genelde oldukça fazla contributor'u vardır
- Belirli bir star / fork: Benzer şekilde, belirli bir sayıda star ve fork'u vardır
- Belirli bir PR sayısı
- gibi şeyler


> Br sonraki plan nedir?

Ben üstteki yorumdaki analizimde, hep kullanıcı odaklı gittim. Yani Türkiye'den kullanıcı sayısı, 20'den fazla PR açanların sayısı vs. gibi şeyler. Hatta bunun için ayrı bir issue açtım: https://github.com/OpenTRFoundation/OpenTR/issues/28
Bu bilgilerle, Türkiye'den açık kaynak katkısı değil de, genel olarak Türkiye'deki GitHub aktivitesi ile ilgili bilgiler edinebiliriz.

Paralelde, üstteki uydurduğum terminolojideki "stratejik açık kaynak proje"nin tanımını yapıp, bu projelerin bilgilerini toplamak için bir çalışma yapmamız gerekiyor. Hatta mümkünse listesini... Yani, şöyle diyebilsek çok güzel olur: "OpenTR olarak, 17 Eylül 2023'te şu 15000 repository bizim için stratejik açık kaynak projedir.". Devamında da, "Türkiye'den bu projelere 1000 kişi katkı vermiş" diyebilsek :) Belirli periyotlarla takip edip, rapor yayınlayabiliriz. Katkıcı sayısını artırmak için yapacağımız çalışmalarda da kullanabiliriz buradan bazı çıkarımlar yapabilirsek.

Biraz uzun oldu yine, ama yorumlarını bekliyorum.

cc @mugekocahan

**Comment by aliok** [comment]
@altuga @mugekocahan Ayrı bir issue açtım "stratejik proje" tanımı için: https://github.com/OpenTRFoundation/OpenTR/issues/29

Not: hedef proje veya başka bir şey de diyebiliriz. Terminoloji uydurmamız şart ama.

**Comment by aliok** [comment]
Bu tamamlandı.

"State of OSS contribution in Turkey" raporu yayınlandı.

Linkler:
- https://state.opentr.foundation/
- https://github.com/OpenTRFoundation/cuttlecat
- https://github.com/OpenTRFoundation/state-of-oss-contribution
- https://github.com/OpenTRFoundation/state-of-oss-contribution-report
