### ISSUE TITLE
OpenTR repository readme dosyasını güncelle

### ISSUE THREAD

**Issue by aliok** [OpenTRFoundation/OpenTR#45]
Repo [readme dosyasında](https://github.com/OpenTRFoundation/OpenTR/blob/main/README.md):
- artık kullanılmayan "açık kaynak, açık işbirliği, açık topluluk" görseli var. silinmesi lazım.
- Logo da güncel logo değil ("Open TR" yazan logo, arada boşluk olan)
-

**Comment by ibrahimdoss** [comment]
@aliok  bunu bana assign edebilir misin ?

**Comment by aliok** [comment]
Fixed by https://github.com/OpenTRFoundation/OpenTR/pull/49
