### ISSUE TITLE
GitHub org profili

### ISSUE THREAD

**Issue by aliok** [OpenTRFoundation/OpenTR#5]
OpenTR'nin [GitHub organizasyonu](https://github.com/OpenTRFoundation)na gittiğimizde bir README dosyası gösterelim.

- İçerik:
  - OpenTR'nin amacı (kısa)
  - Websitesine link
  - Sosyal medya linkleri
- Nasıl yapılacağı burada yazıyor: https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/

**Comment by onuralpszr** [comment]
@aliok  PR : https://github.com/OpenTRFoundation/.github/pull/3
