### ISSUE TITLE
Blog post - OpenTR nedir?

### ISSUE THREAD

**Issue by aliok** [OpenTRFoundation/OpenTR#6]
Bu blogpost, şirketlere ve bireylere kendimizi tanıtırken lazım olacak.

Artık materyallerimiz hazır olduğuna göre ve herkesle OpenTR'yi paylaşmak istediğimize göre, güzel bir blog post çok güzel olur.

OpenTR'nin ne olduğu, amacı, aktiviteleri, vs gibi bilgileri içeren bir blog post yazalım. Bu bilgiler zaten websitesinde var, ama farklı sayfalarda dağınık ve detaylı. Özet bilgi güzel olur.

https://opentr.foundation/blog/2023/06/05/opentr-ba%C5%9Flang%C4%B1%C3%A7/ adresinde bir başlangıç post'u var. Ama üzerinden zaman geçti ve elimizde artık materyaller ve diğer aktivitelerimiz var. Onlardan bahsedelim.

**Comment by aliok** [comment]
cc @ibrahimdoss guncelledim issue'yu hocam.

**Comment by ibrahimdoss** [comment]
pr açtım. geri dönüşleriniz üzerine hemen ekleme veya çıkarma yapabilirim.

**Comment by aliok** [comment]
Done https://github.com/OpenTRFoundation/OpenTR/pull/56
